### ISSUE TITLE
The usage of class and package diagram

### ISSUE THREAD

**Issue by Kekke0** [ChironSZTE/cave-of-chiron#25]
### Task list
Making the dokuentation
(Separated by paragraphs)
- [ ] Quick description about the UML diagrams (3-4 sentences)
- [ ] What are the packages and classes
- [ ] Package diagram, usage and benefits of using it
- [ ] How to make a package diagram
- [ ] Class diagram, usage and benefits of using it
- [ ] How to make a package diagram
