### ISSUE TITLE
The usage of component diagram

### ISSUE THREAD

**Issue by PosLac** [ChironSZTE/cave-of-chiron#27]
### To-do list:

- [x] Short summary about the UML.
- [x] What is a Component Diagram?
- [x] Symbols
- [x] Programs to produce Component Diagrams.
- [x] Examples and other tutorials with links.
