### ISSUE TITLE
UML Structure Diagrams: Object Diagram

### ISSUE THREAD

**Issue by ISlothI** [ChironSZTE/cave-of-chiron#38]
### Tasks
- [x] What is Object Diagram?
- [x] Symbols and notations
- [x] Object Diagram Example
- [x] Useful links
